apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: argocd-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: ARGOCD_OIDC_SECRET
      remoteRef:
        key: op://Infra/authentik-oauth/argocd-client-secret
