apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-secrets
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sabnzbd-secrets
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: op://Infra/sabnzbd/api_key
    - secretKey: nzb_key
      remoteRef:
        key: op://Infra/sabnzbd/nzb_key
