apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-secrets
  namespace: media
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plex-secrets
    creationPolicy: Owner
  data:
    - secretKey: plex_claim
      remoteRef:
        key: plex/claim
