apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: authentik
data:
  infrastructure.yaml: |
    version: 1
    metadata:
      name: Infrastructure SSO
    entries:
      # Groups
      - model: authentik_core.group
        id: group-admins
        identifiers:
          name: admins
        attrs:
          is_superuser: true

      - model: authentik_core.group
        id: group-users
        identifiers:
          name: users
        attrs:
          is_superuser: false

      # OAuth2 Provider - ArgoCD
      - id: provider-argocd
        model: authentik_providers_oauth2.oauth2provider
        identifiers:
          name: ArgoCD
        attrs:
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          client_type: confidential
          client_id: argocd
          client_secret: "eKBc5HB6qpY3TKkWjkZbxp1/vBJewyArTxzlPxtduR8="
          redirect_uris:
            - url: https://argocd.k3s.s33g.uk/auth/callback
              matching_mode: strict
            - url: https://argocd.k3s.s33g.uk/api/dex/callback
              matching_mode: strict
          sub_mode: hashed_user_id
          include_claims_in_id_token: true
          access_code_validity: minutes=1
          access_token_validity: minutes=5
          refresh_token_validity: days=30
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]

      # OAuth2 Provider - Grafana
      - id: provider-grafana
        model: authentik_providers_oauth2.oauth2provider
        identifiers:
          name: Grafana
        attrs:
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          client_type: confidential
          client_id: grafana
          client_secret: "aZlqiS6QNH5A8Jq0cC2K3dLZTXB6WNCXRInqTCE3/rc="
          redirect_uris:
            - url: https://grafana.k3s.s33g.uk/login/generic_oauth
              matching_mode: strict
          sub_mode: hashed_user_id
          include_claims_in_id_token: true
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]

      # Proxy Provider - Forward Auth
      - id: provider-forward-auth
        model: authentik_providers_proxy.proxyprovider
        identifiers:
          name: Forward Auth (Traefik)
        attrs:
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          mode: forward_single
          external_host: https://sso.k3s.s33g.uk

      # Application - ArgoCD
      - id: app-argocd
        model: authentik_core.application
        identifiers:
          slug: argocd
        attrs:
          name: ArgoCD
          provider: !KeyOf provider-argocd
          policy_engine_mode: any
          meta_launch_url: https://argocd.k3s.s33g.uk

      # Application - Grafana
      - id: app-grafana
        model: authentik_core.application
        identifiers:
          slug: grafana
        attrs:
          name: Grafana
          provider: !KeyOf provider-grafana
          policy_engine_mode: any
          meta_launch_url: https://grafana.k3s.s33g.uk

      # Application - Prometheus
      - id: app-prometheus
        model: authentik_core.application
        identifiers:
          slug: prometheus
        attrs:
          name: Prometheus
          provider: !KeyOf provider-forward-auth
          policy_engine_mode: any
          meta_launch_url: https://prometheus.k3s.s33g.uk

      # Application - Alertmanager
      - id: app-alertmanager
        model: authentik_core.application
        identifiers:
          slug: alertmanager
        attrs:
          name: Alertmanager
          provider: !KeyOf provider-forward-auth
          policy_engine_mode: any
          meta_launch_url: https://alertmanager.k3s.s33g.uk

      # Application - Longhorn
      - id: app-longhorn
        model: authentik_core.application
        identifiers:
          slug: longhorn
        attrs:
          name: Longhorn
          provider: !KeyOf provider-forward-auth
          policy_engine_mode: any
          meta_launch_url: https://longhorn.k3s.s33g.uk

      # Application - Gatus
      - id: app-gatus
        model: authentik_core.application
        identifiers:
          slug: gatus
        attrs:
          name: Gatus
          provider: !KeyOf provider-forward-auth
          policy_engine_mode: any
          meta_launch_url: https://gatus.k3s.s33g.uk

      # Application - Uptime Kuma
      - id: app-uptime-kuma
        model: authentik_core.application
        identifiers:
          slug: uptime-kuma
        attrs:
          name: Uptime Kuma
          provider: !KeyOf provider-forward-auth
          policy_engine_mode: any
          meta_launch_url: https://uptime.k3s.s33g.uk

      # Embedded Outpost
      - model: authentik_outposts.outpost
        identifiers:
          managed: goauthentik.io/outposts/embedded
        attrs:
          providers:
            - !KeyOf provider-forward-auth
