# 1Password SDK-based ClusterSecretStore
# Uses Service Account token (ops_...) - no Connect Server needed
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordsdk:
      vault: infra
      auth:
        serviceAccountSecretRef:
          name: onepassword-service-account-token
          namespace: external-secrets
          key: token
