apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      vaults:
        homelab: 1  # Update with your actual vault ID if different
      auth:
        secretRef:
          serviceAccountTokenSecretRef:
            name: onepassword-service-account-token
            namespace: external-secrets
            key: token
