apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    onepasswordSDK:
      vault: Infra
      auth:
        serviceAccountSecretRef:
          name: onepassword-service-account-token
          namespace: external-secrets
          key: token
