apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-oauth-secret
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_CLIENT_SECRET
      remoteRef:
        key: op://Infra/authentik-oauth/grafana-client-secret
