apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpackerr-secret
  namespace: media
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: unpackerr-secret
    creationPolicy: Owner
  data:
    - secretKey: UN_SONARR_0_API_KEY
      remoteRef:
        key: sonarr/api_key
    - secretKey: UN_RADARR_0_API_KEY
      remoteRef:
        key: radarr/api_key
