---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: speedtest-exporter
  namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-exporter
  namespace: monitoring
  labels:
    app: speedtest-exporter
    app.kubernetes.io/name: speedtest-exporter
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-exporter
  template:
    metadata:
      labels:
        app: speedtest-exporter
        app.kubernetes.io/name: speedtest-exporter
    spec:
      serviceAccountName: speedtest-exporter
      containers:
        - name: speedtest-exporter
          image: miguelndecarvalho/speedtest-exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9798
              protocol: TCP
          env:
            - name: SPEEDTEST_INTERVAL
              value: "3600"  # 1 hour in seconds
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  namespace: monitoring
  labels:
    app: speedtest-exporter
    app.kubernetes.io/name: speedtest-exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9798
      targetPort: metrics
      protocol: TCP
  selector:
    app: speedtest-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: speedtest-exporter
  namespace: monitoring
  labels:
    app: speedtest-exporter
    app.kubernetes.io/name: speedtest-exporter
spec:
  selector:
    matchLabels:
      app: speedtest-exporter
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
